### ISSUE TITLE
Do subscription inside App component

### ISSUE THREAD

**Issue by ffxsam** [meteor/simple-todos-react#1]
Nice job on the tutorial, this'll be really helpful for people just getting started with Meteor who want to use React.

One thing: isn't it a more efficient model to put the `Meteor.subscribe` call within `getMeteorData`? I've made a couple changes to `App.jsx`: https://gist.github.com/ffxsam/a93b22d42e48105a8d99

**Comment by stubailo** [comment]
I don't think it's "more efficient", but it could be a better model for people to learn through the tutorial. I'll look into it!

**Comment by stubailo** [comment]
Thanks for the code sample, it looks really good!

**Comment by ffxsam** [comment]
"Efficient" isn't the right word.. maybe just better practice? Putting the subscribe in the component is akin to using `Template.subscribe` in Blaze. I know the tutorial is super small and there's probably no problem putting the subscribe statement outside the component, but it's a good habit to get into I think. :) Cheers!

**Comment by stubailo** [comment]
Yep, I think it would be good for the tutorial to represent as much as possible a good starting point for building a more complicated app!

**Comment by hwillson** [comment]
`Meteor.subscribe` now happens within the newer `withTracker` based HOC, so closing this off - thanks!
