### ISSUE TITLE
Steps 7.1 to 7.3 gets "Access Denied" on all actions

### ISSUE THREAD

**Issue by DanJFletcher** [meteor/simple-todos-react#101]
Following along from 7.1 to 7.3 I am no longer able to make authorized requests even after successfully logging in as the meteorite user.

I ended up having to add this to my `tasks.js` file to get it to work again:

```js
Tasks.allow({
    insert: function (userId, doc) {
        return true;
    },
    update: function (userId, doc, fieldNames, modifier) {
           return true;
    },
    remove: function (userId, doc) {
           return true;
    }
});
```

I'm new to Meteor so I don't know if this is because I'm on a newer version of Meteor than the tutorial originally used but I'm pretty sure I didn't miss any steps along the way. Everything worked until after following the steps from 7.1 to 7.3

**Comment by filipenevola** [comment]
Hey @DanJFletcher , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
