### ISSUE TITLE
Step 2.2 is missing `insertTask`

### ISSUE THREAD

**Issue by DanJFletcher** [meteor/simple-todos-react#102]
In 2.2 There is no definition for `insertTask`. I'm assuming there should be:
```js
function insertTask(text) {
  Tasks.insert({text, createdAt: new Date(), isChecked: false});
}
```

**Comment by williamklingler** [comment]
Can someone please update this in the official docs

**Comment by chris-tse** [comment]
Could the team provide some clarifications on how to PR updates to the code diffs? According to the [readme in meteor/tutorials](https://github.com/meteor/tutorials) the code snippets are generated via the diffs of the actual commit history of this project. How do we go about "modifying" the older commits?

**Comment by filipenevola** [comment]
Hey @DanJFletcher @williamklingler @chris-tse , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
