### ISSUE TITLE
Mistake in Todo App with React Tutorial.

### ISSUE THREAD

**Issue by bushblade** [meteor/simple-todos-react#109]
Hi I'm curious about Meteor since hearing about it on a recent Syntax podcast.
I'm just following along the [Todo App with React](https://www.meteor.com/tutorials/react/creating-an-app) but there seems to be an error on the [collections](https://www.meteor.com/tutorials/react/collections) page of the tutorial, unless I'm missing something?
In Step 2.2 where does the `insertTask` function come from?
It's from this bit of code..
```js


import { Meteor } from 'meteor/meteor';

import Tasks from '/imports/api/tasks';

 

Meteor.startup(() => {

  if (Tasks.find().count() === 0) {

    [

      'First Task',

      'Second Task',

      'Third Task',

      'Fourth Task',

      'Fifth Task',

      'Sixth Task',

      'Seventh Task'

    ].forEach(insertTask) // Where did this function come from?

  }

});

```
Obviously without the insertTask function the tutorial doesn't work as nothing gets inserted into the database.
Am I missing something or is there some part of the tutorial missing?

**Comment by filipenevola** [comment]
Hey @bushblade , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
