### ISSUE TITLE
React Components tutorial not working

### ISSUE THREAD

**Issue by iruslani** [meteor/simple-todos-react#18]
I installed meteor, added react and trying to do the components tutorial but not able to proceed after copying the code in the tutorial. This is the message:

w20160205-12:33:54.289(-8)? (STDERR) 
W20160205-12:33:54.290(-8)? (STDERR) /Users/Iwan/Documents/Demo/MeteorSportup/.meteor/local/build/programs/server/app/MeteorSportup.js:14
W20160205-12:33:54.290(-8)? (STDERR)     React.render(<App />, document.getElementById("render-target"));   // 6
W20160205-12:33:54.290(-8)? (STDERR)                  ^
W20160205-12:33:54.290(-8)? (STDERR) SyntaxError: Unexpected token <
W20160205-12:33:54.290(-8)? (STDERR)     at /Users/Iwan/Documents/Demo/MeteorSportup/.meteor/local/build/programs/server/boot.js:241:30
W20160205-12:33:54.291(-8)? (STDERR)     at Array.forEach (native)
W20160205-12:33:54.291(-8)? (STDERR)     at Function._.each._.forEach (/Users/Iwan/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160205-12:33:54.291(-8)? (STDERR)     at /Users/Iwan/Documents/Demo/MeteorSportup/.meteor/local/build/programs/server/boot.js:137:5
W20160205-12:33:58.031(-8)? (STDERR)  
W20160205-12:33:58.031(-8)? (STDERR) /Users/Iwan/Documents/Demo/MeteorSportup/.meteor/local/build/programs/server/app/MeteorSportup.js:14
W20160205-12:33:58.031(-8)? (STDERR)     React.render(<App />, document.getElementById("render-target"));   // 6
W20160205-12:33:58.031(-8)? (STDERR)                  ^
W20160205-12:33:58.034(-8)? (STDERR) SyntaxError: Unexpected token <
W20160205-12:33:58.034(-8)? (STDERR)     at /Users/Iwan/Documents/Demo/MeteorSportup/.meteor/local/build/programs/server/boot.js:241:30
W20160205-12:33:58.034(-8)? (STDERR)     at Array.forEach (native)
W20160205-12:33:58.034(-8)? (STDERR)     at Function._.each._.forEach (/Users/Iwan/.meteor/packages/meteor-tool/.1.1.10.1b51q9m++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160205-12:33:58.034(-8)? (STDERR)     at /Users/Iwan/Documents/Demo/MeteorSportup/.meteor/local/build/programs/server/boot.js:137:5

I tried:

> meteor update
> meteor remove react
> meteor add react
> meteor --port 9000

Got the same message as above. 

Can someone help please. Looking to get this up and running and learning Meteor.

Thanks
Iwan

**Comment by iruslani** [comment]
Ok NM, found out the issue I had originally started with regular tutorial and added react but I didn't rename my starter JS file to JSX.

**Comment by stubailo** [comment]
Great, glad it got figured out!
