### ISSUE TITLE
In step 4, using findDOMNode is unnecessary, misleading and bad practice

### ISSUE THREAD

**Issue by nsfinkelstein** [meteor/simple-todos-react#19]
The same could just as easily be accomplished by accessing the ref directly, which does not break the component abstraction, e.g.

``` .js
var text = this.refs.textInput.value.trim();
```

I understand you've decided not to take pull requests to the code because you've linked the code in the various steps to particular commits (though rebasing and updating those links should not take too long), so I'll open this issue in case this changes in the future.

Thanks for the tutorials!

**Comment by kevinschaich** [comment]
I also commented this on PR #26, but I'll leave it here as well:

In the next release of tutorials, I don't think this is the correct "React" way to do things. I think there should be some state here like `this.state.newTodoValue` or something similar that should be updated on the change event of the text box:

```javascript
this.state = {newTodoValue: ''}

handleChange(event) {
  this.setState({newTodoValue: event.target.value});
}

handleSubmit(event) {
  event.preventDefault();

  Tasks.insert({
    text: this.state.newTodoValue,
    createdAt: new Date(), // current time
  });

  // Clear form
  this.setState({newTodoValue: ''})
}
```

and in the Render method:

```javascript
<form className="new-task" onSubmit={this.handleSubmit.bind(this)} >
  <input
    type="text"
    ref="textInput"
    placeholder="Type to add new tasks"
    onChange={this.handleChange}
    value={this.state.newTodoValue}
  />
</form>
```

See the [Controlled Components section](https://facebook.github.io/react/docs/forms.html#controlled-components) of the official tutorial.
