### ISSUE TITLE
Alternate method for Blaze template in React component (from new 1.3 Guide)

### ISSUE THREAD

**Issue by mpkliewer** [meteor/simple-todos-react#23]
Tutorial can at some point be updated with new Guide info regarding creating a React wrapper for Blaze templates:

http://guide.meteor.com/react.html#blaze-in-react

It recommends using this package:
 https://github.com/gadicc/meteor-blaze-react-component

Then (in [Step 8.3)](https://github.com/meteor/simple-todos-react/commit/aa6a33ec1a5c203a62ac0c7459ebb378f70bfc81) you can replace:

`<AccountsUIWrapper />`

with:

 `<Blaze template="loginButtons" />`

without having to create the wrapper.

[(From this comment)](https://github.com/meteor/simple-todos-react/commit/cfb42777b34ec46a22101588c646109b77fbf2cd#commitcomment-16947316)

**Comment by bplus** [comment]
Thanks for opening this issue - it helped me a lot.

**Comment by filipenevola** [comment]
Hey @mpkliewer @bplus as this tutorial is React only we are not going to mention blaze here, thank you for your feedback.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
