### ISSUE TITLE
Simple typo on first page of the tutorials

### ISSUE THREAD

**Issue by lancefb** [meteor/simple-todos-react#24]
Shouldn't the second sentence under "ES2015 JavaScript features" read:

"This is **because** Meteor ships by default with support  ... "

instead of:

"This is Meteor ships by default with support  ..."

**Comment by abernix** [comment]
Thanks!  This was fixed with https://github.com/meteor/tutorials/commit/9a9c329336afcbaa2073ab4a38456b024de76057 and visible at https://meteor.com/tutorials/react/!
