### ISSUE TITLE
typo: misspelled hierarchy

### ISSUE THREAD

**Issue by jonescr3** [meteor/simple-todos-react#27]
Just after Step 3.2

To use data from a Meteor collection inside a React component, we can use a Atmosphere package react-meteor-data which allows us to create a "data container" to feed Meteor's reactive data into React's component **heirarchy**.

**Comment by abernix** [comment]
Thanks!  Looks like this was fixed with https://github.com/meteor/tutorials/commit/9b917ce2aac607c512c2f1e6689800840082f208 on the [`tutorials` repo](https://github.com/meteor/tutorials/) (where that text actually lives).  It's live now. :smile:
