### ISSUE TITLE
Just Giving Structure, Flow Route and React Layout to the Simple Todos React Tutorial

### ISSUE THREAD

**Issue by josoroma-zz** [meteor/simple-todos-react#3]
https://github.com/josoroma/Meteor-React-Experiment/blob/master/lib/router.js

Kudos!

**Comment by TylerL-uxai** [comment]
Thank you so much! Spent all night looking for tutorials on how to add react routing to my app

**Comment by hwillson** [comment]
Marking this as a feature request - we should consider replacing `FlowRouter` with `react-router`.

**Comment by filipenevola** [comment]
Hey @josoroma @TylerL-uxai , for now we are not going to add route support for this tutorial but we now have a new format which allows us to have multiple tutorials. Thank you for your feedback.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!

Maybe create a new tutorial using routes?
