### ISSUE TITLE
Uncaught Error: Cannot find module 'Task.jsx (Section 2.3 of Meteor React Simple-Todos)

### ISSUE THREAD

**Issue by m1kegreene** [meteor/simple-todos-react#30]
I've followed the instructions step by step (copy pasted for the entirety) and am having this issue.  The todo list completely disappears off the page and I receive the below error. 

Uncaught Error: Cannot find module 'Task.jsx'require (see screenshot) 

![screen shot 2016-05-14 at 1 30 36 pm](https://cloud.githubusercontent.com/assets/17833721/15269793/78a80cbc-19d8-11e6-917c-c6c4e6c00f7a.png)

**Comment by dilipkumar2k6** [comment]
Can you share your code? I am also following the same however didn't get this error.

**Comment by m1kegreene** [comment]
I've literally followed the instructions step by step, and start having trouble once i replace the starter html code, and delete **client/main.js** and then create three new files

**Comment by dilipkumar2k6** [comment]
For me this is working. If you can simply share your new code inside "client" folder then it may help to understand your issue.

**Comment by m1kegreene** [comment]
main.jsx -> title name fyi

import React from 'react';
import { Meteor } from 'meteor/meteor';
import { render } from 'react-dom';

import App from './imports/ui/App.jsx';

Meteor.startup(() => {
  render(<App />, document.getElementById('render-target'));
});

**Comment by m1kegreene** [comment]
imports/ui/App.jsx -> title name fyi

import React, { Component } from 'react';

import Task from './Task.jsx';

// App component - represents the whole app
export default class App extends Component {
  getTasks() {
    return [
      { _id: 1, text: 'This is task 1' },
      { _id: 2, text: 'This is task 2' },
      { _id: 3, text: 'This is task 3' },
    ];
  }

  renderTasks() {
    return this.getTasks().map((task) => (
      <Task key={task._id} task={task} />
    ));
  }

  render() {
    return (
      <div className="container">
        <header>
          <h1>Todo List</h1>
        </header>

```
    <ul>
      {this.renderTasks()}
    </ul>
  </div>
);
```

  }
}

**Comment by m1kegreene** [comment]
imports/ui/Task.jsx -> title name fyi

import React, { Component, PropTypes } from 'react';

// Task component - represents a single todo item
export default class Task extends Component {
  render() {
    return (
      <li>{this.props.task.text}</li>
    );
  }
}

Task.propTypes = {
  // This component gets the task to display through a React prop.
  // We can use propTypes to indicate it is required
  task: PropTypes.object.isRequired,
};

**Comment by dilipkumar2k6** [comment]
"imports/ui/Task.jpx", is it typo or your real file name? If it is file name then this is the issue. The extension should be "jsx".

**Comment by m1kegreene** [comment]
Whoops, that was just a typo!

Fixed the issue -> imports needs to be a separate folder within client, and then ui within import. App and Task files need to live within UI

Then within main.jsx the walkthrough lists **import App from '../imports/ui/App.jsx';** as the code when it should be **import App from './imports/ui/App.jsx';**

Is this similar to your code? Appreciate the help!

**Comment by dilipkumar2k6** [comment]
Yes :-) I stuck on that issue :-)

**Comment by midnightcodr** [comment]
For me I have to use the following line in imports/ui/App.jsx for the demo to work:

`import Task from './Task';`

Note I am using exactly the same structure as the tutorial - imports/ lives as a sibling to client/, not as a child.

OS: Mac OSX 10.11
Meteor: 1.4.2.3
node: v6.9.2
npm: 4.1.2

**Comment by surjithctly** [comment]
I have also got the same issue. Followed everything literally and got the error when used

`import Task from './Task.jsx';`

But its fixed now when I changed to this: 

`import Task from '/imports/ui/Task.jsx';`

**No idea why the first code did not work.**

The Folder layout was:

```
TodoApp
--- client
--- imports
------ ui
--------- Task.jsx
```

**Comment by spacechimplives** [comment]
I'm having the same issue but neither of your fixes worked for me

**Comment by ahoffmeyer** [comment]
Meteor seems to work with react v0.14 only. So just change the react version within you package.json file to 0.14.9 and it works.

**Comment by DanielMcintosh25** [comment]
Ok make sure the file name is capital "A" for App.js when creating the file and do this for Task.js also.
