### ISSUE TITLE
Stop using `ReactDOM.findDOMNode`

### ISSUE THREAD

**Issue by tmeasday** [meteor/simple-todos-react#31]
See: https://github.com/meteor/simple-todos-react/commit/864c1a4d6ad581b0f6186f609fc079fa110d0a8d#commitcomment-17462750

**Comment by stubailo** [comment]
Related: https://github.com/meteor/simple-todos-react/pull/26

**Comment by orenfromberg** [comment]
also related #45

**Comment by danilopaez** [comment]
Also related #54 .Avoid ref

**Comment by Shelagh-Lewins** [comment]
The code in Section 8.2 https://www.meteor.com/tutorials/react/adding-user-accounts generates errors relating to use of findDOMNode, this.refs and string literals:

```
export default class AccountsUIWrapper extends Component {
  componentDidMount() {
    // Use Meteor Blaze to render login buttons
    this.view = Blaze.render(Template.loginButtons,
      ReactDOM.findDOMNode(this.refs.container));
  }
  componentWillUnmount() {
    // Clean up Blaze view
    Blaze.remove(this.view);
  }
  render() {
    // Just render a placeholder container that will be filled in
    return <span ref="container" />;
  }
}
```
The following code seems to work and doesn't cause linting errors:

```
import React, { Component } from 'react';
import { Template } from 'meteor/templating';
import { Blaze } from 'meteor/blaze';

export default class AccountsUIWrapper extends Component {
	componentDidMount() {
		// Use Meteor Blaze to render login buttons
		this.view = Blaze.render(Template.loginButtons, this.node);
	}
	componentWillUnmount() {
		// Clean up Blaze view
		Blaze.remove(this.view);
	}
	render() {
		// Just render a placeholder container that will be filled in
		return <span ref={node => {this.node = node;}} />;
	}
}
```

**Comment by filipenevola** [comment]
Hey @tmeasday @orenfromberg @danilopaez @Shelagh-Lewins , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
