### ISSUE TITLE
Can't run simple-todos-react 

### ISSUE THREAD

**Issue by ghost** [meteor/simple-todos-react#40]
I ran `git clone https://github.com/meteor/simple-todos-react.git`.
Then I did `cd simple-todos-react` and then `meteor npm install`.
It gives no errors while installing.
When I run `meteor` it shows downloading meteor tool and ends up with this error:

```
$ meteor
/home/webdev/.meteor/packages/meteor-tool/.1.4.1.186av8r++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:165
      throw error;
      ^

Error: ENOENT: no such file or directory, open '/tmp/mt-wpmygz/os.json'
    at Error (native)

```

This also happens every time when I run `meteor update`.So I can't update my project
I tried this on Windows and Ubuntu, It's same on both. How can I solve this?

**Comment by abernix** [comment]
Thanks for reporting this.  This was actually a legit Meteor error at the time.  See https://github.com/meteor/meteor/issues/7806 for the resolution (no actual work is necessary, but you should update your Meteor).  This should be resolved now, so closing.  Happy to reopen if this is not the case! :)
