### ISSUE TITLE
App still depends on blaze-html-templates

### ISSUE THREAD

**Issue by SachaG** [meteor/simple-todos-react#44]
https://github.com/meteor/simple-todos-react/blob/master/.meteor/packages#L10

Maybe this could be replaced with the `static-html` package instead?

**Comment by stubailo** [comment]
We didn't do it in the tutorial because there's a section about accounts-ui in there.

**Comment by SachaG** [comment]
Oh right. I guess this would have to be done along with a switch to https://github.com/studiointeract/accounts-ui then?

**Comment by stubailo** [comment]
Yeah, I think that could be a good way to go. I guess we'll need to restyle it as well.

**Comment by benjamn** [comment]
This is fixed on `master` thanks to https://github.com/meteor/simple-todos-react/commit/baa139e8ea349394f630c81374a4fc576aff389f.

Please note that we rewrite the history of this repository pretty drastically whenever we change the earlier steps, so I wouldn't recommend rebasing an old checkout. Just clone it again.
