### ISSUE TITLE
Idea: remove jquery

### ISSUE THREAD

**Issue by zeroasterisk** [meteor/simple-todos-react#50]
Now that we are using React for UI, could we remove the dependency on `jquery`?  I looked through the meteor codebase for it's usage and it was mostly in deprecated packages.

I tried removing the package, but of course, it's still in `.meteor/versions`

Any idea what the scope of that might be?  It could conceivably be a significant savings in payload sent to the client.

**Comment by stubailo** [comment]
I think the only thing that caused a jQuery dependency would have been `http`. In Meteor 1.5 the bare app skeleton won't have jQuery at all: https://github.com/meteor/meteor/pull/8388

Did you try removing the blaze and accounts UI packages as well?

**Comment by hwillson** [comment]
The jQuery dependency has been removed - thanks!
