### ISSUE TITLE
Migrating from React.PropTypes

### ISSUE THREAD

**Issue by albertovilla** [meteor/simple-todos-react#51]
Importing `PropTypes` from React is now deprecated. The following line in both `App.jsx` and `Task.jsx` needs to be changed:

`import React, { Component, PropTypes } from 'react';`

New line should be:

`import React, { Component } from 'react';`
`import PropTypes from 'prop-types';`

On top of that the `prop-types` package needs to be imported with `npm i prop-types`

**Comment by lukaesch** [comment]
Thanks a lot @albertovilla.
Currently, you can not complete the Meteor ToDo-List tutorial if you don't import PropTypes as described in your comment.

**Comment by hwillson** [comment]
We've decided to remove `PropTypes` from the tutorial completely. A new version will be published shortly - thanks!
