### ISSUE TITLE
Warning: createContainer was deprecated in react-meteor-data@0.2.13. Use withTracker instead.

### ISSUE THREAD

**Issue by iainhallam** [meteor/simple-todos-react#59]
When running the simple-todos-react tutorial, I get this error in the browser console:

```
createContainer was deprecated in react-meteor-data@0.2.13. Use withTracker instead.
```

Further info at https://github.com/meteor/react-packages/tree/devel/packages/react-meteor-data#usage

**Comment by hwillson** [comment]
This has been updated - a new version will be published shortly. Thanks!
