### ISSUE TITLE
meteor-platform deprecated

### ISSUE THREAD

**Issue by Remownz** [meteor/simple-todos-react#6]
The package meteor-platform is marked as deprecated. Which packages should be used instead?

**Comment by stubailo** [comment]
See this document: https://meteor.quip.com/RXFlAk9Rc2xI

Ctrl-F for 'meteor-platform' to find the relevant section.

We should update this tutorial app!

**Comment by hwillson** [comment]
This has been fixed - a new version of the tutorial will be published shortly. Thanks!
