### ISSUE TITLE
Tests shouldn't use arrow function definitions according to 

### ISSUE THREAD

**Issue by Shelagh-Lewins** [meteor/simple-todos-react#62]
The example tests in the React tutorial [simple todos](https://www.meteor.com/tutorials/react/testing) and the todos project example use arrow function in all test definitions, like this:

```
if (Meteor.isServer) {
  describe('Tasks', () => {
    describe('methods', () => {
      it('can delete owned task', () => {
      });
    });
  });
}
```

However the Meteor guide says:

"Note that arrow function use with Mocha is discouraged."

https://guide.meteor.com/testing.html#test-files
http://mochajs.org/#arrow-functions

and shows an example like this:

```
describe('my module', function () {
  it('does something that should be tested', function () {
    // This code will be executed by the test driver when the app is started
    // in the correct mode
  })
})
```

Should the tutorial and examples avoid arrow functions as per the guide? Or have I misunderstood something?

**Comment by Shelagh-Lewins** [comment]
Note this issue was discussed in 2016:

https://github.com/meteor/guide/issues/318
https://github.com/meteor/guide/pull/323

**Comment by filipenevola** [comment]
Hey @Shelagh-Lewins , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
