### ISSUE TITLE
There is no check of the owner of the task

### ISSUE THREAD

**Issue by pihentagy** [meteor/simple-todos-react#64]
https://github.com/meteor/simple-todos-react/blob/1d57eb3a1b8aa32166295b5c27bbef974e3f2221/imports/api/tasks.js#L24

**Comment by MarcelWaldvogel** [comment]
This is in step 10.12 (dcc14bad5)

**Comment by filipenevola** [comment]
Hey @pihentagy @MarcelWaldvogel , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
