### ISSUE TITLE
use renderTasks() can not get data from MongoDB

### ISSUE THREAD

**Issue by hwang12345** [meteor/simple-todos-react#65]
![react2](https://user-images.githubusercontent.com/31944125/40611602-849ea6fe-62a9-11e8-99ed-a0be8ef36ef7.png)
![react1](https://user-images.githubusercontent.com/31944125/40611603-84d6caac-62a9-11e8-983a-b6f18a94c3e0.png)
use renderTasks() can not get data from MongoDB，i can not find the reason.

**Comment by garfieldnate** [comment]
OP didn't give many details on this issue, but I think I have the same one.

I'm following the React-with-Meteor tutorial here: https://guide.meteor.com/react.html#using-with-meteor. When I get to the part where I insert data into Mongo DB, nothing happens in the app. No errors are given in the browser console, and nothing is printed in the terminal. It just does nothing.

I'm uploading my simple-todos app from this point in the tutorial.
[simple-todos.zip](https://github.com/meteor/simple-todos-react/files/2568839/simple-todos.zip)

I am unfortunately unable to run the code in this repo for comparison (it doesn't even start; crashes with NPM issues, but that is a separate ticket).

**Comment by filipenevola** [comment]
Hey @hwang12345 @garfieldnate , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
