### ISSUE TITLE
Can't run this tutorial (Meteor 1.7 doesn't support?)

### ISSUE THREAD

**Issue by andrew128** [meteor/simple-todos-react#66]
/simple-todos-react (master) $ meteor
[[[[[ ~/Desktop/simple-todos-react ]]]]]      

=> Started proxy.                             
                                              
Unable to resolve some modules:

  "@babel/runtime/helpers/interopRequireDefault" in
/simple-todos-react/imports/ui/App.js (web.browser.legacy)
  "@babel/runtime/helpers/inheritsLoose" in   
/simple-todos-react/imports/ui/App.js (web.browser.legacy)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save @babel/runtime    
                                              
Unexpected mongo exit code 62. Restarting.    
Unexpected mongo exit code 62. Restarting.    
Unexpected mongo exit code 62. Restarting.    
Can't start Mongo server.

**Comment by qile11** [comment]
mine too, win10_64

prompt:Mongodb does not support filesystems like nfs
that do not allow file locking

**Comment by jeansordes** [comment]
I can't run the tutorial either but not with the same errors as you

I'm blocked at `meteor mongo`. I can insert, and when I check with `tasks.find();` it shows me that I successfully inserted new data, but it doesn't show anything in the browser. Tasks seems to be empty. I really don't know why :/

edit : when I simply clone the repo, and then run `meteor` in the folder, it shows the same errors as @andrew128 

I'm using Windows 10

**Comment by benjamn** [comment]
Unlike running `meteor create`, when you clone a Meteor application using `git`, you need to run `meteor npm install` to install npm dependencies like `@babel/runtime`. See the [**In a hurry?** section](https://www.meteor.com/tutorials/react/components) of the React tutorial for full instructions.

As for the Mongo issue, that's something else, though it's possible that more recent versions of Meteor (which include more recent versions of MongoDB) no longer have this problem. Try running `meteor update`, or cloning this app again?

**Comment by filipenevola** [comment]
Hey @andrew128 @qile11 @jeansordes , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
