### ISSUE TITLE
icon for  simple todos react

### ISSUE THREAD

**Issue by somratking420** [meteor/simple-todos-react#69]
Hi @meteor , I am a graphic designer, I want to help you in graphic design.

After I review your project, your app is very good. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by benjamn** [comment]
Thanks for the offer @somratking420, but I think we'd like to keep the tutorial as simple as possible, and downloading/adding an icon as part of the tutorial seems like more extra steps than it's worth, if the goal is just to teach folks the basics of Meteor.
