### ISSUE TITLE
issue with meteor add react-meteor-data crashing the app

### ISSUE THREAD

**Issue by Vashidu** [meteor/simple-todos-react#73]
As soon as i added react-meteor-data, the app is crashing:

`=> Modified -- restarting.
W20180916-23:51:42.467(-4)? (STDERR) /home/sopleb/.meteor/packages/meteor-tool/.1.7.0_5.r5qyn1.b1gbd++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20180916-23:51:42.468(-4)? (STDERR)                                            throw(ex);
W20180916-23:51:42.468(-4)? (STDERR)                                            ^
W20180916-23:51:42.469(-4)? (STDERR) 
W20180916-23:51:42.469(-4)? (STDERR) TypeError: Class extends value undefined is not a constructor or null
W20180916-23:51:42.469(-4)? (STDERR)     at ReactMeteorData.jsx (packages/react-meteor-data/ReactMeteorData.jsx:162:36)
W20180916-23:51:42.470(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180916-23:51:42.470(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180916-23:51:42.470(-4)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180916-23:51:42.471(-4)? (STDERR)     at createContainer.jsx (packages/react-meteor-data/createContainer.jsx:1:210)
W20180916-23:51:42.471(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180916-23:51:42.472(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180916-23:51:42.472(-4)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180916-23:51:42.472(-4)? (STDERR)     at react-meteor-data.jsx (packages/react-meteor-data/react-meteor-data.jsx:1:139)
W20180916-23:51:42.473(-4)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:322:7)
W20180916-23:51:42.473(-4)? (STDERR)     at Module.require (packages/modules-runtime.js:224:14)
W20180916-23:51:42.473(-4)? (STDERR)     at require (packages/modules-runtime.js:244:21)
W20180916-23:51:42.473(-4)? (STDERR)     at /home/sopleb/simple-todos/.meteor/local/build/programs/server/packages/react-meteor-data.js:330:15
W20180916-23:51:42.474(-4)? (STDERR)     at /home/sopleb/simple-todos/.meteor/local/build/programs/server/packages/react-meteor-data.js:337:3
W20180916-23:51:42.474(-4)? (STDERR)     at /home/sopleb/simple-todos/.meteor/local/build/programs/server/boot.js:411:36
W20180916-23:51:42.474(-4)? (STDERR)     at Array.forEach (<anonymous>)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.`

**Comment by Vashidu** [comment]
```
sopleb@SVR-DEV:~/simple-todos$ node -v        
v8.10.0
sopleb@SVR-DEV:~/simple-todos$ npm -v
3.5.2

Ubuntu 18.04.1 LTS

**Comment by Vashidu** [comment]
i've stopped the proccess and relaunched meteor and now its not crashing.

**Comment by jeffslofish** [comment]
I ran into the same issue. I believe that something should be said in the tutorial at this step that it might crash and need to be restarted.
