### ISSUE TITLE
Tutorial broken under Meteor 1.8

### ISSUE THREAD

**Issue by philipmjohnson** [meteor/simple-todos-react#76]
With the release of Meteor 1.8, it appears that the React Tutorial (https://www.meteor.com/tutorials/react/creating-an-app) is broken.

After creating the app using `meteor create simple-todos`, you must do the following:

```
meteor remove blaze-html-templates
meteor add static-html
```

**Comment by aylanismello** [comment]
was about to make an issue out of this 💯 ty

**Comment by yinlianghui** [comment]
it just throw error about:'TypeError: _extends is not a function'.
![image](https://user-images.githubusercontent.com/6219465/48330502-b23b3c00-e687-11e8-8fe6-16952e7ce368.png)

**Comment by chbrandt** [comment]
Yes, or --the solution I applied, after [this post](https://forums.meteor.com/t/meteor-html-file-compilation-issue-uncaught-error-target-container-is-not-a-dom-element/44405/5)-- insert
```
import './main.html';
```
at the top of your `client/main.js`.

I'm playing with the _Todo List_ app.

**Comment by undraatb** [comment]
I do confirm that it was required to add `import './main.html';` to `client/main.js`.

**Comment by slowreader87** [comment]
wish i'd read this before trying 3 times from scratch! Works for me too. Thanks!

**Comment by benjamn** [comment]
I've updated this repository to Meteor 1.8.0.1, and will soon push a new version of the React tutorial to meteor.com. If you'd like to help review the changes, please refer to this comment: https://github.com/meteor/simple-todos-react/issues/71#issuecomment-451710776

Thanks for your patience!
