### ISSUE TITLE
TypeError: _extends is not a function

### ISSUE THREAD

**Issue by yinlianghui** [meteor/simple-todos-react#85]
Throw error when i just run the project with 'meteor'.
![image](https://user-images.githubusercontent.com/6219465/48329625-89fe0e00-e684-11e8-8e57-8440949e3fe6.png)

**Comment by benjamn** [comment]
Please try again with the latest version of Meteor, 1.8.0.2:
```ps
git clone git@github.com:meteor/simple-todos-react.git
cd simple-todos-react
meteor npm install
meteor
```
If that doesn't work, feel free to reopen this issue. Thanks!
