### ISSUE TITLE
Simple-todo app react

### ISSUE THREAD

**Issue by lindacharlton** [meteor/simple-todos-react#86]

**Comment by lindacharlton** [comment]
I cannot get my tasks to show up that I put into the form.

**Comment by theranbrig** [comment]
I believe you are talking about when you submit the form.

In this case you need to add prevent default:

I fixed it [here](https://github.com/meteor/simple-todos-react/pull/108).

**Comment by filipenevola** [comment]
Hey @lindacharlton, thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
