### ISSUE TITLE
Why client/main.jsx intead of client/main.js at installation : meteor create --react new-react-app ?

### ISSUE THREAD

**Issue by DonFabiolas** [meteor/simple-todos-react#87]
Hi,

Why client/main.jsx intead of client/main.js at installation : meteor create --react new-react-app ?

I don't know if this link can help : https://github.com/facebook/create-react-app/issues/87#issuecomment-234627904

Thank you

**Comment by filipenevola** [comment]
Hey @FabriceSALAH , I also prefer to use only .js but for now we are keeping jsx as meteor create --react is using it. Thank you for your feedback.

Check the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
