### ISSUE TITLE
Tutorial — Inserting tasks from the server-side database console — browser does not update

### ISSUE THREAD

**Issue by blackslate** [meteor/simple-todos-react#88]
The following instructions on [the tutorial page](https://www.meteor.com/tutorials/react/collections) have no effect:

---

**Inserting tasks from the server-side database console**
Items inside collections are called documents. Let's use the server database console to insert some documents into our collection. While your app is running, in a new terminal tab, go to your app directory and type:

`meteor mongo`
This opens a console into your app's local development database. Into the prompt, type:

`db.tasks.insert({ text: "Hello world!", createdAt: new Date() });`
In your web browser, you will see the UI of your app immediately update to show the new task.

---

Trace from the Terminal window:

```
$ meteor mongo
meteor:PRIMARY> db.tasks.insert({ text: "Hello world!", createdAt: new Date() })

WriteResult({ "nInserted" : 1 })
meteor:PRIMARY> show dbs
admin   0.000GB
config  0.000GB
local   0.000GB
meteor  0.000GB
meteor:PRIMARY> use meteor
switched to db meteor
meteor:PRIMARY> show collections
meteor:PRIMARY> db.tasks.find()
{ "_id" : ObjectId("5c71059d193cf5ef439109c4"), "text" : "Hello world!", "createdAt" : ISODate("2019-02-23T08:34:37.180Z") }
meteor:PRIMARY>

```

In the browser window, http://localhost:3000/ shows simply the header `Todo List`, with no new task

**Comment by blackslate** [comment]
The reason is that in Meteor 1.8.0.2, the scripts inside the `imports` folder are not being run on the server at startup. Adding 1 line to the file at `.../todos/server/main.js` solved the problem:

```
import { Meteor } from 'meteor/meteor';
import { Tasks } from '../imports/api/tasks.js';; // ADDED

Meteor.startup(() => {
  // code to run on server at startup
});
```

**Comment by nilsonmolina** [comment]
Thank you so much! This fixed my issue for [the blaze tutorial page](https://www.meteor.com/tutorials/blaze/collections) as well. This should really be added to the documentation pages!

**Comment by filipenevola** [comment]
Tutorials are already updated.
