### ISSUE TITLE
Meteor-React tutorial: missing step to install Babel package

### ISSUE THREAD

**Issue by blackslate** [meteor/simple-todos-react#89]
I'm following the official [Todo App with React tutorial](https://www.meteor.com/tutorials/react/components). If I follow the steps exactly, after step 2.5, I get an error:

    => Exited with code: 1
                                                  
    Unable to resolve some modules:
    
      "@babel/runtime/helpers/interopRequireDefault" in
    /.../todos/imports/ui/App.js (web.browser.legacy)
      "@babel/runtime/helpers/inheritsLoose" in
    /.../todos/imports/ui/App.js (web.browser.legacy)
    
    If you notice problems related to these missing modules, consider running:
    
      meteor npm install --save @babel/runtime

It seems that the current versions of Meteor and the React npm package do not automatically install Babel, so JSX code is not converted to JS.

It would make life easier for others who want to follow this tutorial if the commands ...

    meteor npm install --save react react-dom
    meteor npm install --save @babel/runtime

... were given together.

**Comment by filipenevola** [comment]
Hey @blackslate , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
