### ISSUE TITLE
"meteor add react-meteor-data" crashes app

### ISSUE THREAD

**Issue by jeffslofish** [meteor/simple-todos-react#90]
Related to #73 and #61 .

It added version 0.2.16 according to the command line output, which according to #61 should have fixed the issue:

```
Jeffreys-MacBook-Air:simple-todos jeff$ meteor add react-meteor-data
                                              
Changes to your project's package version selections:
                                              
react-meteor-data            added, version 0.2.16
tmeasday:check-npm-versions  added, version 0.3.2

                                              
react-meteor-data: React higher-order component for reactively tracking Meteor data
```

however, I took a peek in `.meteor/packages` and it just listed `react-meteor-data` with no version. I'm not sure if that matters, but I thought I would mention it.

**Comment by kakadais** [comment]
I've got simmilar issue and solved by update some npm packages.

"react": "^16.8.6",
"react-dom": "^16.12.0"

And you can see your specific meteor package version in ./meteor/versions file.

**Comment by MonilShiv** [comment]
Installing jQuery solved the problem for me
Use following command to install jQuery
`meteor npm install jquery`

**Comment by filipenevola** [comment]
Hey @jeffslofish @kakadais @MonilShiv, thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
