### ISSUE TITLE
imports account-config.js in main.jsx

### ISSUE THREAD

**Issue by marc-85** [meteor/simple-todos-react#93]
Hello,

I am new to meteor and I am following the simple-todo tutorial. Everything is working fine until I import the accounts-config.js in main.jsx

If I comment the line out, the whole thing starts working again. 

Any ideas why this might be happening?
I am running meteor on an ubuntu 19.04

Many thanks in advance.

**Comment by FrancoisYu** [comment]
I've the same problem after import the accounts-ui. My platform is Mac Catalina and my meteor is 1.9.0.

**Comment by FrancoisYu** [comment]
Got the error msg solved. All you have to do is install the jquery into Meteor and npm with the following command:

meteor add jquery
meteor npm install --save jquery

**Comment by marc-85** [comment]
This seems to work. Thank you very much!
