### ISSUE TITLE
tortilla-master CSS is missing

### ISSUE THREAD

**Issue by jankapunkt** [meteor/simple-todos-react#94]
When cloning and running the app, I can't get a proper css loaded. I also get a `The script has an unsupported MIME type ('text/html').` error:

<img width="1280" alt="Bildschirmfoto 2020-02-17 um 15 01 02" src="https://user-images.githubusercontent.com/1135285/74660512-8cf48200-5196-11ea-9e47-1866adbc95b4.png">

System: MacOS 10.14.6, Chome 77.0.3865.120 64Bit, as well as in FireFox 72.0.2, same os 

Reproduce:

* clone repo
* checkout `tortilla-master`
* npm install and run
* goto localhost:3000

**Comment by filipenevola** [comment]
Hey @jankapunkt , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
