### ISSUE TITLE
tortilla-master isCheck mismatch

### ISSUE THREAD

**Issue by lgmg** [meteor/simple-todos-react#95]
Bad number in counting incomplete Task 
in app.jsx : 
    Mismatch between MongoDb "isChecked" key and fliter. 
    It should be :
`_.set(filter, 'isChecked', false);`
`incompleteTasksCount: Tasks.find({isChecked: {$ne: true}}).count()`

**Comment by DanJFletcher** [comment]
Also note, that when you add the filter you also have to go into `TaskForm.jsx` and update the insert to be:
```js
        Tasks.insert({
          text: text.trim(),
          createdAt: new Date(),
          owner: user._id,
          isChecked: false, // <- this is missing from the tutorial
        });
```

**Comment by 2XL** [comment]
same applies for todo:

https://github.com/meteor/simple-todos-react/commit/8336cc4db3007be941de9c109fbbe4960f246831#diff-59d2d4ad0bd8a50144b6d6b30d01ecccR10

**Comment by filipenevola** [comment]
Hey @2XL, @DanJFletcher, @lgmg , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
