### ISSUE TITLE
tortilla-master : Problem with hide incomplete filter

### ISSUE THREAD

**Issue by lgmg** [meteor/simple-todos-react#96]
When adding a new task, the hide incomplete filter is disabled, it should not.
I don't know where it comes from, it is as if the useState of hideIncomplete variable is re-initialised. is there a problem with the useTracker and useState hook ?

**Comment by lgmg** [comment]
The problem was not due to the hooks but the events passed to the parent ! 
In Apps.jsx, preventDefault() has to be added :
`  const handleSubmit = (event) => {
    event.preventDefault();
    if (!text) return;
    Meteor.call('tasks.insert', text.trim());
    setText("");
  };`

**Comment by filipenevola** [comment]
Hey @lgmg , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
