### ISSUE TITLE
Export default gives an unexpected token error

### ISSUE THREAD

**Issue by Oaksuprem** [meteor/simple-todos-react#97]
![image](https://user-images.githubusercontent.com/38353170/85232972-0681d280-b40c-11ea-9dfb-de5725f1780a.png)
What could be the issue here?

**Comment by filipenevola** [comment]
Hi, do you have ecmascript package in your app, otherwise add it "meteor add ecmascript"

**Comment by filipenevola** [comment]
Hey @Oaksuprem , thank you for your feedback.

I have incorporated your feedback here in this new repo, the new home of react tutorial.

https://github.com/meteor/react-tutorial/ (https://react-tutorial.meteor.com)

It's PR friendly so if you want to make more changes, go ahead there!
